using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Linq;
using System.Text;

namespace Itminus.Tags.SchemaGenerator;

/// <summary>
/// 把消费项目以 AdditionalFiles 传入的 XSD 生成静态字符串常量。
/// 生成 <c>Itminus.Tags.TagsGeneratedSchemas</c>：每个 XSD 一个
/// <c>private const string</c> 常量 + 公开的 <c>GetSchemaContents()</c> 聚合入口。
/// 任何程序集（Core 或各驱动库）都可引用本生成器，把各自的 XSD 编译为常量：
///   - Core：核心 schema（tagsproject.xsd）
///   - 各驱动库：驱动 schema（如 s7.xsd）
/// 相比 EmbeddedResource：不依赖 Assembly.GetManifestResourceStream（反射 API），
/// 对 NativeAOT / trimming 友好，内容在编译期内联。
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class SchemaContentGenerator : IIncrementalGenerator
{
    private const string MetadataKey = "build_metadata.AdditionalFiles.LogicalName";

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // 只处理 .xsd 的 AdditionalFiles。逻辑名：优先取 LogicalName 元数据（若有），
        // 否则从文件路径推导——路径含 drivers 目录则前缀 drivers/，根目录 schema 文件用文件名。
        var schemas = context.AdditionalTextsProvider
            .Where(static t => t.Path.EndsWith(".xsd", StringComparison.OrdinalIgnoreCase))
            .Combine(context.AnalyzerConfigOptionsProvider)
            .Select(static (pair, ct) =>
            {
                var (text, options) = pair;
                var logicalName = options.GetOptions(text).TryGetValue(MetadataKey, out var name)
                    && !string.IsNullOrEmpty(name)
                    ? name
                    : DeriveLogicalName(text.Path);
                var content = text.GetText(ct)?.ToString() ?? string.Empty;
                return new SchemaFile(text.Path, logicalName, content);
            })
            .Where(static s => !string.IsNullOrWhiteSpace(s.LogicalName))
            .Collect();

        context.RegisterSourceOutput(schemas, static (spc, files) =>
        {
            if (files.IsDefaultOrEmpty)
            {
                return;
            }

            // 每个 schema 文件生成一个独立类（类名由文件名派生，程序集间唯一，避免 CS0436 冲突）。
            // 命名空间固定 Itminus.Tags.Generated。
            foreach (var file in files)
            {
                var className = "SchemaContent_" + ToClassNameSuffix(file.LogicalName);
                var builder = new StringBuilder();
                builder.AppendLine("// <auto-generated/>");
                builder.AppendLine("#nullable enable");
                builder.AppendLine("namespace Itminus.Tags.Generated");
                builder.AppendLine("{");
                builder.AppendLine("    /// <summary>");
                builder.AppendLine("    /// 源生成器从 AdditionalFiles 的 XSD 生成的 schema 常量容器");
                builder.AppendLine("    /// （逻辑名 " + Escape(file.LogicalName) + "）。");
                builder.AppendLine("    /// </summary>");
                builder.AppendLine($"    internal static class {className}");
                builder.AppendLine("    {");
                builder.AppendLine($"        private const string Content = {ToStringLiteral(file.Content)};");
                builder.AppendLine();
                builder.AppendLine("        /// <summary>");
                builder.AppendLine("        /// 本 schema 的内容（逻辑名 → 文本）。");
                builder.AppendLine("        /// </summary>");
                builder.AppendLine("        public static IEnumerable<(string LogicalName, string Content)> GetSchemaContents()");
                builder.AppendLine("        {");
                builder.AppendLine($"            yield return (\"{Escape(file.LogicalName)}\", Content);");
                builder.AppendLine("        }");
                builder.AppendLine("    }");
                builder.AppendLine("}");

                spc.AddSource($"Itminus.Tags.SchemaGenerator.{className}.g.cs", SourceText.From(builder.ToString(), Encoding.UTF8));
            }
        });
    }

    /// <summary>
    /// 由逻辑名派生类名后缀：去扩展名，保留字母数字（其余转 _）。
    /// 例：<c>tagsproject.xsd</c> → <c>tagsproject</c>；<c>drivers/s7.xsd</c> → <c>s7</c>。
    /// </summary>
    private static string ToClassNameSuffix(string logicalName)
    {
        var name = logicalName;
        var slash = name.LastIndexOf('/');
        if (slash >= 0)
        {
            name = name.Substring(slash + 1);
        }
        if (name.EndsWith(".xsd", StringComparison.OrdinalIgnoreCase))
        {
            name = name.Substring(0, name.Length - 4);
        }
        var builder = new StringBuilder();
        foreach (var c in name)
        {
            builder.Append(char.IsLetterOrDigit(c) ? c : '_');
        }
        return builder.ToString();
    }

    /// <summary>
    /// 从 AdditionalFiles 的绝对路径推导逻辑名：
    ///  <c>.../Schemas/tagsproject.xsd</c> → <c>tagsproject.xsd</c>
    ///  <c>.../Schemas/drivers/s7.xsd</c> → <c>drivers/s7.xsd</c>
    /// </summary>
    private static string DeriveLogicalName(string path)
    {
        var normalized = path.Replace('\\', '/');
        var fileName = System.IO.Path.GetFileName(path);
        if (normalized.EndsWith("/drivers/" + fileName, StringComparison.OrdinalIgnoreCase))
        {
            return "drivers/" + fileName;
        }
        return fileName;
    }

    private static string ToStringLiteral(string content)
    {
        // 优先 raw string literal（内容不含三个连续双引号时）；否则退化为转义字符串。
        if (!content.Contains("\"\"\""))
        {
            var trimmed = content.TrimEnd('\r', '\n');
            return "\"\"\"\n" + trimmed + "\n\"\"\"";
        }
        return "\"" + Escape(content) + "\"";
    }

    private static string Escape(string s) => s
        .Replace("\\", "\\\\")
        .Replace("\"", "\\\"")
        .Replace("\r", "\\r")
        .Replace("\n", "\\n")
        .Replace("\t", "\\t");

    private sealed class SchemaFile
    {
        public SchemaFile(string path, string logicalName, string content)
        {
            Path = path;
            LogicalName = logicalName;
            Content = content;
        }

        public string Path { get; set; }
        public string LogicalName { get; set; }
        public string Content { get; set; }
    }
}
