<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\Itminus.Tags.Core\Itminus.Tags.Core.csproj" >
		</ProjectReference>
	</ItemGroup>
</Project>
