<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <TargetFramework>net8.0</TargetFramework>
	  <ImplicitUsings>enable</ImplicitUsings>
	  <OutputType>Library</OutputType>
	  <LangVersion>latest</LangVersion>
	  <Nullable>enable</Nullable>
	  <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Itminus.Tags.ModbusTcp\Itminus.Tags.ModbusTcp.csproj" />
  </ItemGroup>
	<Import Project="..\..\.paket\Paket.Restore.targets" />

</Project>
