<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
	<NuGetAudit>false</NuGetAudit>
	<LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Itminus.Tags.ComScanner\Itminus.Tags.ComScanner.csproj" />
    <ProjectReference Include="..\Itminus.Tags.Hjzk\Itminus.Tags.Hjzk.csproj" />
    <ProjectReference Include="..\Itminus.Tags.ModbusTcp\Itminus.Tags.ModbusTcp.csproj" />
    <ProjectReference Include="..\Itminus.Tags.OpcUaClient\Itminus.Tags.OpcUaClient.csproj" />
    <ProjectReference Include="..\Itminus.Tags.RxExtensions\Itminus.Tags.RxExtensions.csproj" />
    <ProjectReference Include="..\Itminus.Tags.R3Extensions\Itminus.Tags.R3Extensions.csproj" />
    <ProjectReference Include="..\Itminus.Tags.S7\Itminus.Tags.S7.csproj" />
    <ProjectReference Include="..\Itminus.Tags.ZLan\Itminus.Tags.ZLan.csproj" />
    <ProjectReference Include="..\Itminus.Tags\Itminus.Tags.csproj" />
    <ProjectReference Include="..\Itminus.Tags.McpServer\Itminus.Tags.McpServer.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="ComTags\ComProjTests\ComProjSelectorTests.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ComTags\ComScriptTests\ComScriptTags2.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ComTags\ComScriptTests\ComScriptTags.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ComTags\ComScriptTests\ComScriptEmptyTags.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ModbusTags\index.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ModbusTags\DirectTags\index.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="OpcUaClientTags\index.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="OpcUaClientTags\DirectTags\index.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="S7Tags\index.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="S7Tags\DirectTags\index.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TagUnions\index.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="HjzkTags\index.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="ZLanTags\index.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <Import Project="..\..\.paket\Paket.Restore.targets" />
</Project>