<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ServerGarbageCollection>false</ServerGarbageCollection>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  </PropertyGroup>

	<PropertyGroup>
		<StaticFilesFolderName>Samples.Plugin1</StaticFilesFolderName>
	</PropertyGroup>
	
  <ItemGroup>
	  <ContentWithTargetPath Include="Samples.Plugin1\**\*.*">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		  <TargetPath>$(StaticFilesFolderName)\%(RecursiveDir)%(Filename)%(Extension)</TargetPath>
	  </ContentWithTargetPath>
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\Itminus.Tags.BlazorLib\Itminus.Tags.BlazorLib.csproj" />
    <ProjectReference Include="..\Itminus.Tags.ComScanner\Itminus.Tags.ComScanner.csproj" />
    <ProjectReference Include="..\Itminus.Tags.Hjzk\Itminus.Tags.Hjzk.csproj" />
    <ProjectReference Include="..\Itminus.Tags.ModbusTcp\Itminus.Tags.ModbusTcp.csproj" />
    <ProjectReference Include="..\Itminus.Tags.OpcUaClient\Itminus.Tags.OpcUaClient.csproj" />
    <ProjectReference Include="..\Itminus.Tags.RxExtensions\Itminus.Tags.RxExtensions.csproj" />
    <ProjectReference Include="..\Itminus.Tags.S7\Itminus.Tags.S7.csproj" />
    <ProjectReference Include="..\Itminus.Tags.ZLan\Itminus.Tags.ZLan.csproj" />
    <ProjectReference Include="..\Itminus.Tags\Itminus.Tags.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="index-plugin.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="index.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="index2.xml">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <Import Project="..\.paket\Paket.Restore.targets" />
</Project>