# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: PushOrPR On Master Branch

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev"  ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.102
    - name: Restore Tool dependencies
      working-directory: .
      run: dotnet tool restore
    - name: Restore dependencies
      working-directory: .
      run: dotnet paket restore
    - name: build 
      working-directory: .
      run: dotnet build Itminus.Tags.sln
    - name: test
      working-directory: .
      run: dotnet test