# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Release

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: 'Release Version'
        required: true
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.102
    - name: Restore Tool dependencies
      working-directory: .
      run: dotnet tool restore
    - name: Restore dependencies
      working-directory: .
      run: dotnet paket restore
    - name: build and test
      working-directory: 
      run: dotnet build 
    - name: push
      working-directory: ./src
      run: dotnet pwsh ./publish-packages.ps1 -packageVersion ${{ github.event.inputs.releaseVersion }} 
      env:
        NugetSource: ${{ secrets.NUGET_SOURCE }}
        NugetApiKey: ${{ secrets.NUGET_KEY }}
